### ISSUE TITLE
How value stay within the circle

### ISSUE THREAD

**Issue by gugoan** [braunmar/yii2-easypiechart#1]
Hello,
How to make the percentage value stay within the circle?
(in my example here it was over)

```
    <?php
    use braunmar\yii\easypiechart\EasyPieChart;
    echo EasyPieChart::widget([
        'content' => Html::tag('p', 'Rede 01 - 85%'),
        'element' => 'div',
        'options' => ['data-percent' => 85, 'class' => 'easypiechart'],
        'pluginOptions' => [
            'scaleColor' => false,
            'trackColor' => '#d6d6d6',
            'lineWidth' => 8,
            'barColor' => '#0C3D44',
            'size' => 120,
        ],
    ]);
    ?>
```

**Comment by braunmar** [comment]
Hello,

this plugin for now render only HTML with attributes for easypiechart plugin. For center percentage into circle you will need some simple CSS.

In your case with size 120 will be:
(I use flex in this case, but you can use another technique for center).

``` css
.your-selector .easypiechart {
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
    height: 120px;
    width: 120px;
}

.your-selector .easypiechart p {
    position: absolute;
    margin: 0;
}
```

In the future I want convert plugin to PHP 7.1 (7.2) and add features like that with CSS. I will add this to examples. Thanks for issue.
